### ISSUE TITLE
Example to get temperature?

### ISSUE THREAD

**Issue by pkazmier** [JeremyProffit/EchoPhotonBridge#1]
What are the function arguments in the temperature callback function? I have a couple of photons with temperature sensors I’d love to hook up. Just couldn’t figure out how I was supposed to interpret the args?

**Comment by JeremyProffitt** [comment]
Let me know if this helps, basically, if either of the bool vars are set, you return that particular temperature.  Otherwise, you set the temp for the themostat (or what ever you are working with).

int functionTemp(int device, bool requestCurrentTemp, bool requestSetTemp, int temperature, int changeAmount, String rawParameters)
{
    if (requestCurrentTemp) return currentTemp;
    if (requestSetTemp) return setTemp;
    setTemp = temperature;
    thermostat = true;
    updateThermostatDisplay("On");
    return 0;
}

**Comment by JeremyProffitt** [comment]
You can also look at this example:  https://go.particle.io/shared_apps/599ddba5bfe32b087c000fef

**Comment by pkazmier** [comment]
Thanks!
