### ISSUE TITLE
Is there a way to toggle a device on and off?

### ISSUE THREAD

**Issue by processedmeat** [JeremyProffit/EchoPhotonBridge#2]
Hi Jeremy, great app.  I'm making a garage door server and I was wondering if there was a way to quickly toggle a device with one command instead of having to turn it on and then having to turn it off.  I want Alexa to trigger a relay that is connected to my garage door opener.  Thanks for your help.

**Comment by zak333008** [comment]
Just be careful nobody will shout "Alexa, open the door". She would let strangers in. 
but to tiger your garage instead of this:
digitalWrite(3, (onOff) ? LOW : HIGH); 
you can write 
digitalWrite(3, HIGH); delay (1000); digitalWrite(3, LOW);

**Comment by JeremyProffitt** [comment]
the best way to do this is have a global variable and use the loop and millis function, since the alexa skill waits for a response from the particle to give an "OK" response, using a delay in the functionOnOff will likely cause the skill to timeout and then return a not okay to alexa, everything will work, but it's a poor user experience.  The solution I recomend for the best user experiance is to open the door when you get the call, then set a time delay and check for that time in the loop function to release the relay. 

 the code below Plus the startup() from on the onoff demo should work.

int pushAgainInMillis = -1;

int functionOnOff(int device, bool onOff, String rawParameters)
{
    digitalWrite(D7,  HIGH);
    pushAgainInMillis = Millis() + (1000 * 3);  //current time plus 3 minutes.
}

loop() {
  if (pushAgainInMillis > -1 && pushAgainInMills > Millis()) {
  digitalWrite(D7, LOW);
  pushAgainInMillis = -1;
}
